# cargo-deny configuration file
# See https://embarkstudios.github.io/cargo-deny/index.html

[graph]
# Dependency graph targets
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "x86_64-apple-darwin" },
    { triple = "aarch64-apple-darwin" },
]

[advisories]
# Security vulnerability database config
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/RustSec/advisory-db"]

# Security vulnerabilities
vulnerability = "deny"
# Unmaintained crates
unmaintained = "warn"
# Unsound crates
unsound = "warn"
# Security notices
notice = "warn"

# Allow certain security advisories
ignore = [
    # Allow these temporarily while we work on upgrades
]

[licenses]
# License policy
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0", 
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "CC0-1.0",
]
deny = [
    "GPL-2.0",
    "GPL-3.0",
    "AGPL-1.0",
    "AGPL-3.0",
    "LGPL-2.0",
    "LGPL-2.1",
    "LGPL-3.0",
]
copyleft = "deny"

# License clarity requirements
confidence-threshold = 0.8
exceptions = []

[bans]
# Ban specific crates entirely
deny = [
    # Examples of banned crates (none currently)
    # { name = "openssl", version = "*", reason = "use rustls instead" },
]

# Allow multiple versions but warn
multiple-versions = "warn"

# Wildcard dependencies
wildcards = "deny"

# Allow certain duplicates
allow = [
    # Temporary allowances for common transitive deps
    { name = "windows_x86_64_msvc" },
    { name = "windows_x86_64_gnu" },
    { name = "windows_i686_msvc" },
    { name = "syn", version = "1.0" },  # Many crates still use syn 1.0
    { name = "unicode-normalization" },
]

# Deny git dependencies (force published crates)
deny-git = []

# Skip certain crates from analysis
skip = []

[sources]
# Source control
unknown-registry = "warn"
unknown-git = "deny"

# Allow crates.io
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

# No git dependencies unless explicitly allowed
allow-git = []