//! Artifact management system for enhanced agents
//!
//! This module provides comprehensive artifact management capabilities including
//! storage, retrieval, versioning, and metadata tracking for code artifacts
//! generated by the enhanced agent system.

pub mod manager;
pub mod display;

pub use manager::{
    ArtifactManager, EnhancedArtifact, ArtifactMetadata, VersionInfo,
    QualityMetrics, UsageStats, StorageInfo, ArtifactRelationships,
    VersionType, ArtifactStats, ArtifactManagerError, ArtifactSearchCriteria,
};

pub use display::{
    ArtifactDisplay, ArtifactViewerState, ArtifactDisplayConfig,
    DisplayTheme, ViewMode, ComparisonState, ArtifactDiff,
    DiffHunk, DiffLine, DiffLineType, DiffStats,
};