[general]
log_level = "info"
auto_save = true
backup_enabled = true
telemetry_enabled = false

[agents]
max_concurrent_agents = 5
agent_timeout_seconds = 300
default_agent_priority = "normal"
custom_agents = []

[agents.notification_settings]
enabled = true
sound_enabled = false
desktop_notifications = true
auto_dismiss_timeout = 5000

[codegen]
template_directories = []

[codegen.default_style]
indentation = "spaces"
indent_size = 4
line_length = 100
naming_convention = "auto"
include_comments = true
include_type_hints = true

[codegen.language_preferences]

[codegen.ai_model_settings]
default_provider = "ollama"
default_model = "llama3.2:latest"
context_window_size = 8192
temperature = 0.7
max_tokens = 1000

[codegen.ai_model_settings.ollama]
endpoint = "http://localhost:11434"
timeout_seconds = 300
max_retries = 3
default_model = "llama3.2:latest"

[shell]
command_timeout = 30
history_enabled = true

[shell.environment_variables]

[shell.custom_commands]

[ui]
theme = "default"
color_scheme = "dark"
font_size = 14
show_line_numbers = true
show_timestamps = true
auto_scroll = true

[ui.panel_layout]
output_panel_percentage = 70
agent_panel_percentage = 30
notification_panel_height = 5
input_panel_height = 3

[keybindings]
agent_view = "a"
enter = "Enter"
escape = "Esc"
quit = "q"
backspace = "Backspace"
command_mode = ":"
input_mode = "i"
scroll_up = "k"
page_up = "u"
page_down = "d"
scroll_down = "j"
settings = "s"
