[package]
name = "demo-api-server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
warp = "0.3"
anyhow = "1.0"
uuid = { version = "1.0", features = ["v4"] }
